#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_HD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Helpdesk")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHD_Departamento(HD_Departamento instance);
    partial void UpdateHD_Departamento(HD_Departamento instance);
    partial void DeleteHD_Departamento(HD_Departamento instance);
    partial void InsertHD_Publicacion(HD_Publicacion instance);
    partial void UpdateHD_Publicacion(HD_Publicacion instance);
    partial void DeleteHD_Publicacion(HD_Publicacion instance);
    partial void InsertHD_Usuario(HD_Usuario instance);
    partial void UpdateHD_Usuario(HD_Usuario instance);
    partial void DeleteHD_Usuario(HD_Usuario instance);
    partial void InsertHD_Publicacion_Comentario(HD_Publicacion_Comentario instance);
    partial void UpdateHD_Publicacion_Comentario(HD_Publicacion_Comentario instance);
    partial void DeleteHD_Publicacion_Comentario(HD_Publicacion_Comentario instance);
    partial void InsertHD_Usuario_Seguidore(HD_Usuario_Seguidore instance);
    partial void UpdateHD_Usuario_Seguidore(HD_Usuario_Seguidore instance);
    partial void DeleteHD_Usuario_Seguidore(HD_Usuario_Seguidore instance);
    partial void InsertHD_Publicacion_Usuario(HD_Publicacion_Usuario instance);
    partial void UpdateHD_Publicacion_Usuario(HD_Publicacion_Usuario instance);
    partial void DeleteHD_Publicacion_Usuario(HD_Publicacion_Usuario instance);
    partial void InsertHD_TipoNotificacion(HD_TipoNotificacion instance);
    partial void UpdateHD_TipoNotificacion(HD_TipoNotificacion instance);
    partial void DeleteHD_TipoNotificacion(HD_TipoNotificacion instance);
    partial void InsertHD_Usuario_Notificacion(HD_Usuario_Notificacion instance);
    partial void UpdateHD_Usuario_Notificacion(HD_Usuario_Notificacion instance);
    partial void DeleteHD_Usuario_Notificacion(HD_Usuario_Notificacion instance);
    partial void InsertHD_Estado(HD_Estado instance);
    partial void UpdateHD_Estado(HD_Estado instance);
    partial void DeleteHD_Estado(HD_Estado instance);
    partial void InsertHD_Problema(HD_Problema instance);
    partial void UpdateHD_Problema(HD_Problema instance);
    partial void DeleteHD_Problema(HD_Problema instance);
    partial void InsertHD_Solicitud(HD_Solicitud instance);
    partial void UpdateHD_Solicitud(HD_Solicitud instance);
    partial void DeleteHD_Solicitud(HD_Solicitud instance);
    partial void InsertHD_Solicitud_Comentario(HD_Solicitud_Comentario instance);
    partial void UpdateHD_Solicitud_Comentario(HD_Solicitud_Comentario instance);
    partial void DeleteHD_Solicitud_Comentario(HD_Solicitud_Comentario instance);
    #endregion
		
		public DBDataContext() : 
				base(global::DB_HD.Properties.Settings.Default.HelpdeskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HD_Departamento> HD_Departamentos
		{
			get
			{
				return this.GetTable<HD_Departamento>();
			}
		}
		
		public System.Data.Linq.Table<HD_Publicacion> HD_Publicacions
		{
			get
			{
				return this.GetTable<HD_Publicacion>();
			}
		}
		
		public System.Data.Linq.Table<HD_Usuario> HD_Usuarios
		{
			get
			{
				return this.GetTable<HD_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<HD_Publicacion_Comentario> HD_Publicacion_Comentarios
		{
			get
			{
				return this.GetTable<HD_Publicacion_Comentario>();
			}
		}
		
		public System.Data.Linq.Table<HD_Usuario_Seguidore> HD_Usuario_Seguidores
		{
			get
			{
				return this.GetTable<HD_Usuario_Seguidore>();
			}
		}
		
		public System.Data.Linq.Table<HD_Publicacion_Usuario> HD_Publicacion_Usuarios
		{
			get
			{
				return this.GetTable<HD_Publicacion_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<HD_TipoNotificacion> HD_TipoNotificacions
		{
			get
			{
				return this.GetTable<HD_TipoNotificacion>();
			}
		}
		
		public System.Data.Linq.Table<HD_Usuario_Notificacion> HD_Usuario_Notificacions
		{
			get
			{
				return this.GetTable<HD_Usuario_Notificacion>();
			}
		}
		
		public System.Data.Linq.Table<HD_Estado> HD_Estados
		{
			get
			{
				return this.GetTable<HD_Estado>();
			}
		}
		
		public System.Data.Linq.Table<HD_Problema> HD_Problemas
		{
			get
			{
				return this.GetTable<HD_Problema>();
			}
		}
		
		public System.Data.Linq.Table<HD_Solicitud> HD_Solicituds
		{
			get
			{
				return this.GetTable<HD_Solicitud>();
			}
		}
		
		public System.Data.Linq.Table<HD_Solicitud_Comentario> HD_Solicitud_Comentarios
		{
			get
			{
				return this.GetTable<HD_Solicitud_Comentario>();
			}
		}
		
		public System.Data.Linq.Table<VW_Resumen> VW_Resumens
		{
			get
			{
				return this.GetTable<VW_Resumen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Departamento")]
	public partial class HD_Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _departamento_id;
		
		private string _departamento;
		
		private EntitySet<HD_Usuario> _HD_Usuarios;
		
		private EntitySet<HD_Problema> _HD_Problemas;
		
		private EntitySet<HD_Solicitud> _HD_Solicituds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepartamento_idChanging(int value);
    partial void Ondepartamento_idChanged();
    partial void OndepartamentoChanging(string value);
    partial void OndepartamentoChanged();
    #endregion
		
		public HD_Departamento()
		{
			this._HD_Usuarios = new EntitySet<HD_Usuario>(new Action<HD_Usuario>(this.attach_HD_Usuarios), new Action<HD_Usuario>(this.detach_HD_Usuarios));
			this._HD_Problemas = new EntitySet<HD_Problema>(new Action<HD_Problema>(this.attach_HD_Problemas), new Action<HD_Problema>(this.detach_HD_Problemas));
			this._HD_Solicituds = new EntitySet<HD_Solicitud>(new Action<HD_Solicitud>(this.attach_HD_Solicituds), new Action<HD_Solicitud>(this.detach_HD_Solicituds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int departamento_id
		{
			get
			{
				return this._departamento_id;
			}
			set
			{
				if ((this._departamento_id != value))
				{
					this.Ondepartamento_idChanging(value);
					this.SendPropertyChanging();
					this._departamento_id = value;
					this.SendPropertyChanged("departamento_id");
					this.Ondepartamento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string departamento
		{
			get
			{
				return this._departamento;
			}
			set
			{
				if ((this._departamento != value))
				{
					this.OndepartamentoChanging(value);
					this.SendPropertyChanging();
					this._departamento = value;
					this.SendPropertyChanged("departamento");
					this.OndepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Usuario", Storage="_HD_Usuarios", ThisKey="departamento_id", OtherKey="departamento_id")]
		public EntitySet<HD_Usuario> HD_Usuarios
		{
			get
			{
				return this._HD_Usuarios;
			}
			set
			{
				this._HD_Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Problema", Storage="_HD_Problemas", ThisKey="departamento_id", OtherKey="departamento_id")]
		public EntitySet<HD_Problema> HD_Problemas
		{
			get
			{
				return this._HD_Problemas;
			}
			set
			{
				this._HD_Problemas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Solicitud", Storage="_HD_Solicituds", ThisKey="departamento_id", OtherKey="departamento_id")]
		public EntitySet<HD_Solicitud> HD_Solicituds
		{
			get
			{
				return this._HD_Solicituds;
			}
			set
			{
				this._HD_Solicituds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Usuarios(HD_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = this;
		}
		
		private void detach_HD_Usuarios(HD_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = null;
		}
		
		private void attach_HD_Problemas(HD_Problema entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = this;
		}
		
		private void detach_HD_Problemas(HD_Problema entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = null;
		}
		
		private void attach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = this;
		}
		
		private void detach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Publicacion")]
	public partial class HD_Publicacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _publicacion_id;
		
		private string _encabezado;
		
		private string _contenido;
		
		private bool _activo;
		
		private System.DateTime _fecha;
		
		private int _usuario_id;
		
		private EntitySet<HD_Publicacion_Comentario> _HD_Publicacion_Comentarios;
		
		private EntitySet<HD_Publicacion_Usuario> _HD_Publicacion_Usuarios;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpublicacion_idChanging(int value);
    partial void Onpublicacion_idChanged();
    partial void OnencabezadoChanging(string value);
    partial void OnencabezadoChanged();
    partial void OncontenidoChanging(string value);
    partial void OncontenidoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    #endregion
		
		public HD_Publicacion()
		{
			this._HD_Publicacion_Comentarios = new EntitySet<HD_Publicacion_Comentario>(new Action<HD_Publicacion_Comentario>(this.attach_HD_Publicacion_Comentarios), new Action<HD_Publicacion_Comentario>(this.detach_HD_Publicacion_Comentarios));
			this._HD_Publicacion_Usuarios = new EntitySet<HD_Publicacion_Usuario>(new Action<HD_Publicacion_Usuario>(this.attach_HD_Publicacion_Usuarios), new Action<HD_Publicacion_Usuario>(this.detach_HD_Publicacion_Usuarios));
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publicacion_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int publicacion_id
		{
			get
			{
				return this._publicacion_id;
			}
			set
			{
				if ((this._publicacion_id != value))
				{
					this.Onpublicacion_idChanging(value);
					this.SendPropertyChanging();
					this._publicacion_id = value;
					this.SendPropertyChanged("publicacion_id");
					this.Onpublicacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encabezado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string encabezado
		{
			get
			{
				return this._encabezado;
			}
			set
			{
				if ((this._encabezado != value))
				{
					this.OnencabezadoChanging(value);
					this.SendPropertyChanging();
					this._encabezado = value;
					this.SendPropertyChanged("encabezado");
					this.OnencabezadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contenido", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string contenido
		{
			get
			{
				return this._contenido;
			}
			set
			{
				if ((this._contenido != value))
				{
					this.OncontenidoChanging(value);
					this.SendPropertyChanging();
					this._contenido = value;
					this.SendPropertyChanged("contenido");
					this.OncontenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Publicacion_HD_Publicacion_Comentario", Storage="_HD_Publicacion_Comentarios", ThisKey="publicacion_id", OtherKey="publicacion_id")]
		public EntitySet<HD_Publicacion_Comentario> HD_Publicacion_Comentarios
		{
			get
			{
				return this._HD_Publicacion_Comentarios;
			}
			set
			{
				this._HD_Publicacion_Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Publicacion_HD_Publicacion_Usuario", Storage="_HD_Publicacion_Usuarios", ThisKey="publicacion_id", OtherKey="publicacion_id")]
		public EntitySet<HD_Publicacion_Usuario> HD_Publicacion_Usuarios
		{
			get
			{
				return this._HD_Publicacion_Usuarios;
			}
			set
			{
				this._HD_Publicacion_Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion", Storage="_HD_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Publicacions.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Publicacions.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Publicacion_Comentarios(HD_Publicacion_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Publicacion = this;
		}
		
		private void detach_HD_Publicacion_Comentarios(HD_Publicacion_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Publicacion = null;
		}
		
		private void attach_HD_Publicacion_Usuarios(HD_Publicacion_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Publicacion = this;
		}
		
		private void detach_HD_Publicacion_Usuarios(HD_Publicacion_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Publicacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Usuarios")]
	public partial class HD_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuario_id;
		
		private string _usuario;
		
		private string _clave;
		
		private string _nombres;
		
		private string _apellidos;
		
		private bool _activo;
		
		private int _departamento_id;
		
		private EntitySet<HD_Publicacion> _HD_Publicacions;
		
		private EntitySet<HD_Publicacion_Comentario> _HD_Publicacion_Comentarios;
		
		private EntitySet<HD_Usuario_Seguidore> _HD_Usuario_Seguidores;
		
		private EntitySet<HD_Usuario_Seguidore> _HD_Usuario_Seguidores1;
		
		private EntitySet<HD_Publicacion_Usuario> _HD_Publicacion_Usuarios;
		
		private EntitySet<HD_Usuario_Notificacion> _HD_Usuario_Notificacions;
		
		private EntitySet<HD_Solicitud> _HD_Solicituds;
		
		private EntitySet<HD_Solicitud> _HD_Solicituds1;
		
		private EntitySet<HD_Solicitud_Comentario> _HD_Solicitud_Comentarios;
		
		private EntityRef<HD_Departamento> _HD_Departamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    partial void Ondepartamento_idChanging(int value);
    partial void Ondepartamento_idChanged();
    #endregion
		
		public HD_Usuario()
		{
			this._HD_Publicacions = new EntitySet<HD_Publicacion>(new Action<HD_Publicacion>(this.attach_HD_Publicacions), new Action<HD_Publicacion>(this.detach_HD_Publicacions));
			this._HD_Publicacion_Comentarios = new EntitySet<HD_Publicacion_Comentario>(new Action<HD_Publicacion_Comentario>(this.attach_HD_Publicacion_Comentarios), new Action<HD_Publicacion_Comentario>(this.detach_HD_Publicacion_Comentarios));
			this._HD_Usuario_Seguidores = new EntitySet<HD_Usuario_Seguidore>(new Action<HD_Usuario_Seguidore>(this.attach_HD_Usuario_Seguidores), new Action<HD_Usuario_Seguidore>(this.detach_HD_Usuario_Seguidores));
			this._HD_Usuario_Seguidores1 = new EntitySet<HD_Usuario_Seguidore>(new Action<HD_Usuario_Seguidore>(this.attach_HD_Usuario_Seguidores1), new Action<HD_Usuario_Seguidore>(this.detach_HD_Usuario_Seguidores1));
			this._HD_Publicacion_Usuarios = new EntitySet<HD_Publicacion_Usuario>(new Action<HD_Publicacion_Usuario>(this.attach_HD_Publicacion_Usuarios), new Action<HD_Publicacion_Usuario>(this.detach_HD_Publicacion_Usuarios));
			this._HD_Usuario_Notificacions = new EntitySet<HD_Usuario_Notificacion>(new Action<HD_Usuario_Notificacion>(this.attach_HD_Usuario_Notificacions), new Action<HD_Usuario_Notificacion>(this.detach_HD_Usuario_Notificacions));
			this._HD_Solicituds = new EntitySet<HD_Solicitud>(new Action<HD_Solicitud>(this.attach_HD_Solicituds), new Action<HD_Solicitud>(this.detach_HD_Solicituds));
			this._HD_Solicituds1 = new EntitySet<HD_Solicitud>(new Action<HD_Solicitud>(this.attach_HD_Solicituds1), new Action<HD_Solicitud>(this.detach_HD_Solicituds1));
			this._HD_Solicitud_Comentarios = new EntitySet<HD_Solicitud_Comentario>(new Action<HD_Solicitud_Comentario>(this.attach_HD_Solicitud_Comentarios), new Action<HD_Solicitud_Comentario>(this.detach_HD_Solicitud_Comentarios));
			this._HD_Departamento = default(EntityRef<HD_Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_id", DbType="Int NOT NULL")]
		public int departamento_id
		{
			get
			{
				return this._departamento_id;
			}
			set
			{
				if ((this._departamento_id != value))
				{
					if (this._HD_Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepartamento_idChanging(value);
					this.SendPropertyChanging();
					this._departamento_id = value;
					this.SendPropertyChanged("departamento_id");
					this.Ondepartamento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion", Storage="_HD_Publicacions", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Publicacion> HD_Publicacions
		{
			get
			{
				return this._HD_Publicacions;
			}
			set
			{
				this._HD_Publicacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion_Comentario", Storage="_HD_Publicacion_Comentarios", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Publicacion_Comentario> HD_Publicacion_Comentarios
		{
			get
			{
				return this._HD_Publicacion_Comentarios;
			}
			set
			{
				this._HD_Publicacion_Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Seguidore", Storage="_HD_Usuario_Seguidores", ThisKey="usuario_id", OtherKey="seguidor_id")]
		public EntitySet<HD_Usuario_Seguidore> HD_Usuario_
		{
			get
			{
				return this._HD_Usuario_Seguidores;
			}
			set
			{
				this._HD_Usuario_Seguidores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Seguidore1", Storage="_HD_Usuario_Seguidores1", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Usuario_Seguidore> HD_Usuario_Seguidores
		{
			get
			{
				return this._HD_Usuario_Seguidores1;
			}
			set
			{
				this._HD_Usuario_Seguidores1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion_Usuario", Storage="_HD_Publicacion_Usuarios", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Publicacion_Usuario> HD_Publicacion_Usuarios
		{
			get
			{
				return this._HD_Publicacion_Usuarios;
			}
			set
			{
				this._HD_Publicacion_Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Notificacion", Storage="_HD_Usuario_Notificacions", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Usuario_Notificacion> HD_Usuario_Notificacions
		{
			get
			{
				return this._HD_Usuario_Notificacions;
			}
			set
			{
				this._HD_Usuario_Notificacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud", Storage="_HD_Solicituds", ThisKey="usuario_id", OtherKey="usr_asignado_id")]
		public EntitySet<HD_Solicitud> HD_Solicituds
		{
			get
			{
				return this._HD_Solicituds;
			}
			set
			{
				this._HD_Solicituds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud1", Storage="_HD_Solicituds1", ThisKey="usuario_id", OtherKey="usr_solicita_id")]
		public EntitySet<HD_Solicitud> HD_Solicituds1
		{
			get
			{
				return this._HD_Solicituds1;
			}
			set
			{
				this._HD_Solicituds1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud_Comentario", Storage="_HD_Solicitud_Comentarios", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<HD_Solicitud_Comentario> HD_Solicitud_Comentarios
		{
			get
			{
				return this._HD_Solicitud_Comentarios;
			}
			set
			{
				this._HD_Solicitud_Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Usuario", Storage="_HD_Departamento", ThisKey="departamento_id", OtherKey="departamento_id", IsForeignKey=true)]
		public HD_Departamento HD_Departamento
		{
			get
			{
				return this._HD_Departamento.Entity;
			}
			set
			{
				HD_Departamento previousValue = this._HD_Departamento.Entity;
				if (((previousValue != value) 
							|| (this._HD_Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Departamento.Entity = null;
						previousValue.HD_Usuarios.Remove(this);
					}
					this._HD_Departamento.Entity = value;
					if ((value != null))
					{
						value.HD_Usuarios.Add(this);
						this._departamento_id = value.departamento_id;
					}
					else
					{
						this._departamento_id = default(int);
					}
					this.SendPropertyChanged("HD_Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Publicacions(HD_Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Publicacions(HD_Publicacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
		
		private void attach_HD_Publicacion_Comentarios(HD_Publicacion_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Publicacion_Comentarios(HD_Publicacion_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
		
		private void attach_HD_Usuario_Seguidores(HD_Usuario_Seguidore entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Seguidor = this;
		}
		
		private void detach_HD_Usuario_Seguidores(HD_Usuario_Seguidore entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Seguidor = null;
		}
		
		private void attach_HD_Usuario_Seguidores1(HD_Usuario_Seguidore entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Usuario_Seguidores1(HD_Usuario_Seguidore entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
		
		private void attach_HD_Publicacion_Usuarios(HD_Publicacion_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Publicacion_Usuarios(HD_Publicacion_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
		
		private void attach_HD_Usuario_Notificacions(HD_Usuario_Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Usuario_Notificacions(HD_Usuario_Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
		
		private void attach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Asignado = this;
		}
		
		private void detach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Asignado = null;
		}
		
		private void attach_HD_Solicituds1(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Solicita = this;
		}
		
		private void detach_HD_Solicituds1(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario_Solicita = null;
		}
		
		private void attach_HD_Solicitud_Comentarios(HD_Solicitud_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = this;
		}
		
		private void detach_HD_Solicitud_Comentarios(HD_Solicitud_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Publicacion_Comentarios")]
	public partial class HD_Publicacion_Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _comentario_id;
		
		private int _publicacion_id;
		
		private int _usuario_id;
		
		private string _comentario;
		
		private System.DateTime _fecha;
		
		private EntityRef<HD_Publicacion> _HD_Publicacion;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomentario_idChanging(int value);
    partial void Oncomentario_idChanged();
    partial void Onpublicacion_idChanging(int value);
    partial void Onpublicacion_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public HD_Publicacion_Comentario()
		{
			this._HD_Publicacion = default(EntityRef<HD_Publicacion>);
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int comentario_id
		{
			get
			{
				return this._comentario_id;
			}
			set
			{
				if ((this._comentario_id != value))
				{
					this.Oncomentario_idChanging(value);
					this.SendPropertyChanging();
					this._comentario_id = value;
					this.SendPropertyChanged("comentario_id");
					this.Oncomentario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publicacion_id", DbType="Int NOT NULL")]
		public int publicacion_id
		{
			get
			{
				return this._publicacion_id;
			}
			set
			{
				if ((this._publicacion_id != value))
				{
					if (this._HD_Publicacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpublicacion_idChanging(value);
					this.SendPropertyChanging();
					this._publicacion_id = value;
					this.SendPropertyChanged("publicacion_id");
					this.Onpublicacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Publicacion_HD_Publicacion_Comentario", Storage="_HD_Publicacion", ThisKey="publicacion_id", OtherKey="publicacion_id", IsForeignKey=true)]
		public HD_Publicacion HD_Publicacion
		{
			get
			{
				return this._HD_Publicacion.Entity;
			}
			set
			{
				HD_Publicacion previousValue = this._HD_Publicacion.Entity;
				if (((previousValue != value) 
							|| (this._HD_Publicacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Publicacion.Entity = null;
						previousValue.HD_Publicacion_Comentarios.Remove(this);
					}
					this._HD_Publicacion.Entity = value;
					if ((value != null))
					{
						value.HD_Publicacion_Comentarios.Add(this);
						this._publicacion_id = value.publicacion_id;
					}
					else
					{
						this._publicacion_id = default(int);
					}
					this.SendPropertyChanged("HD_Publicacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion_Comentario", Storage="_HD_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Publicacion_Comentarios.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Publicacion_Comentarios.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Usuario_Seguidores")]
	public partial class HD_Usuario_Seguidore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _useg_id;
		
		private int _usuario_id;
		
		private int _seguidor_id;
		
		private System.DateTime _fecha;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
		private EntityRef<HD_Usuario> _HD_Usuario1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuseg_idChanging(int value);
    partial void Onuseg_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void Onseguidor_idChanging(int value);
    partial void Onseguidor_idChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public HD_Usuario_Seguidore()
		{
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			this._HD_Usuario1 = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useg_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int useg_id
		{
			get
			{
				return this._useg_id;
			}
			set
			{
				if ((this._useg_id != value))
				{
					this.Onuseg_idChanging(value);
					this.SendPropertyChanging();
					this._useg_id = value;
					this.SendPropertyChanged("useg_id");
					this.Onuseg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seguidor_id", DbType="Int NOT NULL")]
		public int seguidor_id
		{
			get
			{
				return this._seguidor_id;
			}
			set
			{
				if ((this._seguidor_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onseguidor_idChanging(value);
					this.SendPropertyChanging();
					this._seguidor_id = value;
					this.SendPropertyChanged("seguidor_id");
					this.Onseguidor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Seguidore", Storage="_HD_Usuario", ThisKey="seguidor_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario_Seguidor
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Usuario_.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Usuario_.Add(this);
						this._seguidor_id = value.usuario_id;
					}
					else
					{
						this._seguidor_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario_Seguidor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Seguidore1", Storage="_HD_Usuario1", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario1.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario1.Entity = null;
						previousValue.HD_Usuario_Seguidores.Remove(this);
					}
					this._HD_Usuario1.Entity = value;
					if ((value != null))
					{
						value.HD_Usuario_Seguidores.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Publicacion_Usuario")]
	public partial class HD_Publicacion_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _puid;
		
		private int _publicacion_id;
		
		private int _usuario_id;
		
		private System.DateTime _fecha;
		
		private EntityRef<HD_Publicacion> _HD_Publicacion;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpuidChanging(int value);
    partial void OnpuidChanged();
    partial void Onpublicacion_idChanging(int value);
    partial void Onpublicacion_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    #endregion
		
		public HD_Publicacion_Usuario()
		{
			this._HD_Publicacion = default(EntityRef<HD_Publicacion>);
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int puid
		{
			get
			{
				return this._puid;
			}
			set
			{
				if ((this._puid != value))
				{
					this.OnpuidChanging(value);
					this.SendPropertyChanging();
					this._puid = value;
					this.SendPropertyChanged("puid");
					this.OnpuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publicacion_id", DbType="Int NOT NULL")]
		public int publicacion_id
		{
			get
			{
				return this._publicacion_id;
			}
			set
			{
				if ((this._publicacion_id != value))
				{
					if (this._HD_Publicacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpublicacion_idChanging(value);
					this.SendPropertyChanging();
					this._publicacion_id = value;
					this.SendPropertyChanged("publicacion_id");
					this.Onpublicacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Publicacion_HD_Publicacion_Usuario", Storage="_HD_Publicacion", ThisKey="publicacion_id", OtherKey="publicacion_id", IsForeignKey=true)]
		public HD_Publicacion HD_Publicacion
		{
			get
			{
				return this._HD_Publicacion.Entity;
			}
			set
			{
				HD_Publicacion previousValue = this._HD_Publicacion.Entity;
				if (((previousValue != value) 
							|| (this._HD_Publicacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Publicacion.Entity = null;
						previousValue.HD_Publicacion_Usuarios.Remove(this);
					}
					this._HD_Publicacion.Entity = value;
					if ((value != null))
					{
						value.HD_Publicacion_Usuarios.Add(this);
						this._publicacion_id = value.publicacion_id;
					}
					else
					{
						this._publicacion_id = default(int);
					}
					this.SendPropertyChanged("HD_Publicacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Publicacion_Usuario", Storage="_HD_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Publicacion_Usuarios.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Publicacion_Usuarios.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_TipoNotificacion")]
	public partial class HD_TipoNotificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tipo_id;
		
		private string _tipo;
		
		private EntitySet<HD_Usuario_Notificacion> _HD_Usuario_Notificacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontipo_idChanging(int value);
    partial void Ontipo_idChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public HD_TipoNotificacion()
		{
			this._HD_Usuario_Notificacions = new EntitySet<HD_Usuario_Notificacion>(new Action<HD_Usuario_Notificacion>(this.attach_HD_Usuario_Notificacions), new Action<HD_Usuario_Notificacion>(this.detach_HD_Usuario_Notificacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tipo_id
		{
			get
			{
				return this._tipo_id;
			}
			set
			{
				if ((this._tipo_id != value))
				{
					this.Ontipo_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_id = value;
					this.SendPropertyChanged("tipo_id");
					this.Ontipo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_TipoNotificacion_HD_Usuario_Notificacion", Storage="_HD_Usuario_Notificacions", ThisKey="tipo_id", OtherKey="tipo_id")]
		public EntitySet<HD_Usuario_Notificacion> HD_Usuario_Notificacions
		{
			get
			{
				return this._HD_Usuario_Notificacions;
			}
			set
			{
				this._HD_Usuario_Notificacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Usuario_Notificacions(HD_Usuario_Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_TipoNotificacion = this;
		}
		
		private void detach_HD_Usuario_Notificacions(HD_Usuario_Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.HD_TipoNotificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Usuario_Notificacion")]
	public partial class HD_Usuario_Notificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _notId;
		
		private int _tipo_id;
		
		private int _usuario_id;
		
		private System.DateTime _fecha;
		
		private string _comentario;
		
		private int _id;
		
		private bool _visto;
		
		private EntityRef<HD_TipoNotificacion> _HD_TipoNotificacion;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnotIdChanging(int value);
    partial void OnnotIdChanged();
    partial void Ontipo_idChanging(int value);
    partial void Ontipo_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvistoChanging(bool value);
    partial void OnvistoChanged();
    #endregion
		
		public HD_Usuario_Notificacion()
		{
			this._HD_TipoNotificacion = default(EntityRef<HD_TipoNotificacion>);
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int notId
		{
			get
			{
				return this._notId;
			}
			set
			{
				if ((this._notId != value))
				{
					this.OnnotIdChanging(value);
					this.SendPropertyChanging();
					this._notId = value;
					this.SendPropertyChanged("notId");
					this.OnnotIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_id", DbType="Int NOT NULL")]
		public int tipo_id
		{
			get
			{
				return this._tipo_id;
			}
			set
			{
				if ((this._tipo_id != value))
				{
					if (this._HD_TipoNotificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontipo_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_id = value;
					this.SendPropertyChanged("tipo_id");
					this.Ontipo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visto", DbType="Bit NOT NULL")]
		public bool visto
		{
			get
			{
				return this._visto;
			}
			set
			{
				if ((this._visto != value))
				{
					this.OnvistoChanging(value);
					this.SendPropertyChanging();
					this._visto = value;
					this.SendPropertyChanged("visto");
					this.OnvistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_TipoNotificacion_HD_Usuario_Notificacion", Storage="_HD_TipoNotificacion", ThisKey="tipo_id", OtherKey="tipo_id", IsForeignKey=true)]
		public HD_TipoNotificacion HD_TipoNotificacion
		{
			get
			{
				return this._HD_TipoNotificacion.Entity;
			}
			set
			{
				HD_TipoNotificacion previousValue = this._HD_TipoNotificacion.Entity;
				if (((previousValue != value) 
							|| (this._HD_TipoNotificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_TipoNotificacion.Entity = null;
						previousValue.HD_Usuario_Notificacions.Remove(this);
					}
					this._HD_TipoNotificacion.Entity = value;
					if ((value != null))
					{
						value.HD_Usuario_Notificacions.Add(this);
						this._tipo_id = value.tipo_id;
					}
					else
					{
						this._tipo_id = default(int);
					}
					this.SendPropertyChanged("HD_TipoNotificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Usuario_Notificacion", Storage="_HD_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Usuario_Notificacions.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Usuario_Notificacions.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Estado")]
	public partial class HD_Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _estado_id;
		
		private string _estado;
		
		private EntitySet<HD_Solicitud> _HD_Solicituds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onestado_idChanging(int value);
    partial void Onestado_idChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public HD_Estado()
		{
			this._HD_Solicituds = new EntitySet<HD_Solicitud>(new Action<HD_Solicitud>(this.attach_HD_Solicituds), new Action<HD_Solicitud>(this.detach_HD_Solicituds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int estado_id
		{
			get
			{
				return this._estado_id;
			}
			set
			{
				if ((this._estado_id != value))
				{
					this.Onestado_idChanging(value);
					this.SendPropertyChanging();
					this._estado_id = value;
					this.SendPropertyChanged("estado_id");
					this.Onestado_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Estado_HD_Solicitud", Storage="_HD_Solicituds", ThisKey="estado_id", OtherKey="estado_id")]
		public EntitySet<HD_Solicitud> HD_Solicituds
		{
			get
			{
				return this._HD_Solicituds;
			}
			set
			{
				this._HD_Solicituds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Estado = this;
		}
		
		private void detach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Problema")]
	public partial class HD_Problema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _problema_id;
		
		private string _problema;
		
		private int _departamento_id;
		
		private EntitySet<HD_Solicitud> _HD_Solicituds;
		
		private EntityRef<HD_Departamento> _HD_Departamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproblema_idChanging(int value);
    partial void Onproblema_idChanged();
    partial void OnproblemaChanging(string value);
    partial void OnproblemaChanged();
    partial void Ondepartamento_idChanging(int value);
    partial void Ondepartamento_idChanged();
    #endregion
		
		public HD_Problema()
		{
			this._HD_Solicituds = new EntitySet<HD_Solicitud>(new Action<HD_Solicitud>(this.attach_HD_Solicituds), new Action<HD_Solicitud>(this.detach_HD_Solicituds));
			this._HD_Departamento = default(EntityRef<HD_Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problema_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int problema_id
		{
			get
			{
				return this._problema_id;
			}
			set
			{
				if ((this._problema_id != value))
				{
					this.Onproblema_idChanging(value);
					this.SendPropertyChanging();
					this._problema_id = value;
					this.SendPropertyChanged("problema_id");
					this.Onproblema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problema", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string problema
		{
			get
			{
				return this._problema;
			}
			set
			{
				if ((this._problema != value))
				{
					this.OnproblemaChanging(value);
					this.SendPropertyChanging();
					this._problema = value;
					this.SendPropertyChanged("problema");
					this.OnproblemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_id", DbType="Int NOT NULL")]
		public int departamento_id
		{
			get
			{
				return this._departamento_id;
			}
			set
			{
				if ((this._departamento_id != value))
				{
					if (this._HD_Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepartamento_idChanging(value);
					this.SendPropertyChanging();
					this._departamento_id = value;
					this.SendPropertyChanged("departamento_id");
					this.Ondepartamento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Problema_HD_Solicitud", Storage="_HD_Solicituds", ThisKey="problema_id", OtherKey="problema_id")]
		public EntitySet<HD_Solicitud> HD_Solicituds
		{
			get
			{
				return this._HD_Solicituds;
			}
			set
			{
				this._HD_Solicituds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Problema", Storage="_HD_Departamento", ThisKey="departamento_id", OtherKey="departamento_id", IsForeignKey=true)]
		public HD_Departamento HD_Departamento
		{
			get
			{
				return this._HD_Departamento.Entity;
			}
			set
			{
				HD_Departamento previousValue = this._HD_Departamento.Entity;
				if (((previousValue != value) 
							|| (this._HD_Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Departamento.Entity = null;
						previousValue.HD_Problemas.Remove(this);
					}
					this._HD_Departamento.Entity = value;
					if ((value != null))
					{
						value.HD_Problemas.Add(this);
						this._departamento_id = value.departamento_id;
					}
					else
					{
						this._departamento_id = default(int);
					}
					this.SendPropertyChanged("HD_Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Problema = this;
		}
		
		private void detach_HD_Solicituds(HD_Solicitud entity)
		{
			this.SendPropertyChanging();
			entity.HD_Problema = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Solicitud")]
	public partial class HD_Solicitud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _solicitud_id;
		
		private System.DateTime _fecha;
		
		private int _usr_solicita_id;
		
		private System.Nullable<int> _usr_asignado_id;
		
		private string _titulo;
		
		private string _descripcion;
		
		private int _problema_id;
		
		private int _departamento_id;
		
		private int _estado_id;
		
		private EntitySet<HD_Solicitud_Comentario> _HD_Solicitud_Comentarios;
		
		private EntityRef<HD_Departamento> _HD_Departamento;
		
		private EntityRef<HD_Estado> _HD_Estado;
		
		private EntityRef<HD_Problema> _HD_Problema;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
		private EntityRef<HD_Usuario> _HD_Usuario1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onusr_solicita_idChanging(int value);
    partial void Onusr_solicita_idChanged();
    partial void Onusr_asignado_idChanging(System.Nullable<int> value);
    partial void Onusr_asignado_idChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onproblema_idChanging(int value);
    partial void Onproblema_idChanged();
    partial void Ondepartamento_idChanging(int value);
    partial void Ondepartamento_idChanged();
    partial void Onestado_idChanging(int value);
    partial void Onestado_idChanged();
    #endregion
		
		public HD_Solicitud()
		{
			this._HD_Solicitud_Comentarios = new EntitySet<HD_Solicitud_Comentario>(new Action<HD_Solicitud_Comentario>(this.attach_HD_Solicitud_Comentarios), new Action<HD_Solicitud_Comentario>(this.detach_HD_Solicitud_Comentarios));
			this._HD_Departamento = default(EntityRef<HD_Departamento>);
			this._HD_Estado = default(EntityRef<HD_Estado>);
			this._HD_Problema = default(EntityRef<HD_Problema>);
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			this._HD_Usuario1 = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_solicita_id", DbType="Int NOT NULL")]
		public int usr_solicita_id
		{
			get
			{
				return this._usr_solicita_id;
			}
			set
			{
				if ((this._usr_solicita_id != value))
				{
					if (this._HD_Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusr_solicita_idChanging(value);
					this.SendPropertyChanging();
					this._usr_solicita_id = value;
					this.SendPropertyChanged("usr_solicita_id");
					this.Onusr_solicita_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_asignado_id", DbType="Int NOT NULL")]
		public System.Nullable<int> usr_asignado_id
		{
			get
			{
				return this._usr_asignado_id;
			}
			set
			{
				if ((this._usr_asignado_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusr_asignado_idChanging(value);
					this.SendPropertyChanging();
					this._usr_asignado_id = value;
					this.SendPropertyChanged("usr_asignado_id");
					this.Onusr_asignado_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problema_id", DbType="Int NOT NULL")]
		public int problema_id
		{
			get
			{
				return this._problema_id;
			}
			set
			{
				if ((this._problema_id != value))
				{
					if (this._HD_Problema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproblema_idChanging(value);
					this.SendPropertyChanging();
					this._problema_id = value;
					this.SendPropertyChanged("problema_id");
					this.Onproblema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_id", DbType="Int NOT NULL")]
		public int departamento_id
		{
			get
			{
				return this._departamento_id;
			}
			set
			{
				if ((this._departamento_id != value))
				{
					if (this._HD_Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepartamento_idChanging(value);
					this.SendPropertyChanging();
					this._departamento_id = value;
					this.SendPropertyChanged("departamento_id");
					this.Ondepartamento_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_id", DbType="Int NOT NULL")]
		public int estado_id
		{
			get
			{
				return this._estado_id;
			}
			set
			{
				if ((this._estado_id != value))
				{
					if (this._HD_Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onestado_idChanging(value);
					this.SendPropertyChanging();
					this._estado_id = value;
					this.SendPropertyChanged("estado_id");
					this.Onestado_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Solicitud_HD_Solicitud_Comentario", Storage="_HD_Solicitud_Comentarios", ThisKey="solicitud_id", OtherKey="solicitud_id")]
		public EntitySet<HD_Solicitud_Comentario> HD_Solicitud_Comentarios
		{
			get
			{
				return this._HD_Solicitud_Comentarios;
			}
			set
			{
				this._HD_Solicitud_Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Departamento_HD_Solicitud", Storage="_HD_Departamento", ThisKey="departamento_id", OtherKey="departamento_id", IsForeignKey=true)]
		public HD_Departamento HD_Departamento
		{
			get
			{
				return this._HD_Departamento.Entity;
			}
			set
			{
				HD_Departamento previousValue = this._HD_Departamento.Entity;
				if (((previousValue != value) 
							|| (this._HD_Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Departamento.Entity = null;
						previousValue.HD_Solicituds.Remove(this);
					}
					this._HD_Departamento.Entity = value;
					if ((value != null))
					{
						value.HD_Solicituds.Add(this);
						this._departamento_id = value.departamento_id;
					}
					else
					{
						this._departamento_id = default(int);
					}
					this.SendPropertyChanged("HD_Departamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Estado_HD_Solicitud", Storage="_HD_Estado", ThisKey="estado_id", OtherKey="estado_id", IsForeignKey=true)]
		public HD_Estado HD_Estado
		{
			get
			{
				return this._HD_Estado.Entity;
			}
			set
			{
				HD_Estado previousValue = this._HD_Estado.Entity;
				if (((previousValue != value) 
							|| (this._HD_Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Estado.Entity = null;
						previousValue.HD_Solicituds.Remove(this);
					}
					this._HD_Estado.Entity = value;
					if ((value != null))
					{
						value.HD_Solicituds.Add(this);
						this._estado_id = value.estado_id;
					}
					else
					{
						this._estado_id = default(int);
					}
					this.SendPropertyChanged("HD_Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Problema_HD_Solicitud", Storage="_HD_Problema", ThisKey="problema_id", OtherKey="problema_id", IsForeignKey=true)]
		public HD_Problema HD_Problema
		{
			get
			{
				return this._HD_Problema.Entity;
			}
			set
			{
				HD_Problema previousValue = this._HD_Problema.Entity;
				if (((previousValue != value) 
							|| (this._HD_Problema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Problema.Entity = null;
						previousValue.HD_Solicituds.Remove(this);
					}
					this._HD_Problema.Entity = value;
					if ((value != null))
					{
						value.HD_Solicituds.Add(this);
						this._problema_id = value.problema_id;
					}
					else
					{
						this._problema_id = default(int);
					}
					this.SendPropertyChanged("HD_Problema");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud", Storage="_HD_Usuario", ThisKey="usr_asignado_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario_Asignado
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Solicituds.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Solicituds.Add(this);
						this._usr_asignado_id = value.usuario_id;
					}
					else
					{
						this._usr_asignado_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("HD_Usuario_Asignado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud1", Storage="_HD_Usuario1", ThisKey="usr_solicita_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario_Solicita
		{
			get
			{
				return this._HD_Usuario1.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario1.Entity = null;
						previousValue.HD_Solicituds1.Remove(this);
					}
					this._HD_Usuario1.Entity = value;
					if ((value != null))
					{
						value.HD_Solicituds1.Add(this);
						this._usr_solicita_id = value.usuario_id;
					}
					else
					{
						this._usr_solicita_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario_Solicita");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HD_Solicitud_Comentarios(HD_Solicitud_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Solicitud = this;
		}
		
		private void detach_HD_Solicitud_Comentarios(HD_Solicitud_Comentario entity)
		{
			this.SendPropertyChanging();
			entity.HD_Solicitud = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HD_Solicitud_Comentarios")]
	public partial class HD_Solicitud_Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _comentario_id;
		
		private string _comentario;
		
		private int _solicitud_id;
		
		private int _usuario_id;
		
		private System.DateTime _fecha;
		
		private string _rutaFile;
		
		private EntityRef<HD_Solicitud> _HD_Solicitud;
		
		private EntityRef<HD_Usuario> _HD_Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomentario_idChanging(int value);
    partial void Oncomentario_idChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void Onsolicitud_idChanging(int value);
    partial void Onsolicitud_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnrutaFileChanging(string value);
    partial void OnrutaFileChanged();
    #endregion
		
		public HD_Solicitud_Comentario()
		{
			this._HD_Solicitud = default(EntityRef<HD_Solicitud>);
			this._HD_Usuario = default(EntityRef<HD_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int comentario_id
		{
			get
			{
				return this._comentario_id;
			}
			set
			{
				if ((this._comentario_id != value))
				{
					this.Oncomentario_idChanging(value);
					this.SendPropertyChanging();
					this._comentario_id = value;
					this.SendPropertyChanged("comentario_id");
					this.Oncomentario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitud_id", DbType="Int NOT NULL")]
		public int solicitud_id
		{
			get
			{
				return this._solicitud_id;
			}
			set
			{
				if ((this._solicitud_id != value))
				{
					if (this._HD_Solicitud.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsolicitud_idChanging(value);
					this.SendPropertyChanging();
					this._solicitud_id = value;
					this.SendPropertyChanged("solicitud_id");
					this.Onsolicitud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._HD_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rutaFile", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string rutaFile
		{
			get
			{
				return this._rutaFile;
			}
			set
			{
				if ((this._rutaFile != value))
				{
					this.OnrutaFileChanging(value);
					this.SendPropertyChanging();
					this._rutaFile = value;
					this.SendPropertyChanged("rutaFile");
					this.OnrutaFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Solicitud_HD_Solicitud_Comentario", Storage="_HD_Solicitud", ThisKey="solicitud_id", OtherKey="solicitud_id", IsForeignKey=true)]
		public HD_Solicitud HD_Solicitud
		{
			get
			{
				return this._HD_Solicitud.Entity;
			}
			set
			{
				HD_Solicitud previousValue = this._HD_Solicitud.Entity;
				if (((previousValue != value) 
							|| (this._HD_Solicitud.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Solicitud.Entity = null;
						previousValue.HD_Solicitud_Comentarios.Remove(this);
					}
					this._HD_Solicitud.Entity = value;
					if ((value != null))
					{
						value.HD_Solicitud_Comentarios.Add(this);
						this._solicitud_id = value.solicitud_id;
					}
					else
					{
						this._solicitud_id = default(int);
					}
					this.SendPropertyChanged("HD_Solicitud");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HD_Usuario_HD_Solicitud_Comentario", Storage="_HD_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public HD_Usuario HD_Usuario
		{
			get
			{
				return this._HD_Usuario.Entity;
			}
			set
			{
				HD_Usuario previousValue = this._HD_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._HD_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HD_Usuario.Entity = null;
						previousValue.HD_Solicitud_Comentarios.Remove(this);
					}
					this._HD_Usuario.Entity = value;
					if ((value != null))
					{
						value.HD_Solicitud_Comentarios.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("HD_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Resumen")]
	public partial class VW_Resumen
	{
		
		private string _estado;
		
		private System.Nullable<int> _cantidad;
		
		public VW_Resumen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
